### ISSUE TITLE
nginx: [emerg] unknown "endpoints_api_userinfo" variable

### ISSUE THREAD

**Issue by nielskrijger** [GoogleCloudPlatform/endpoints-samples#21]
Hi,

While trying out the examples for k8s, we tried all four esp_echo_*.yaml examples. When trying out the last example (esp_echo_custom_config_gke.yaml) we got the following error in the esp container:
```
nginx: [warn] Failed to open trusted CA certificates file: /etc/nginx/custom/trusted-ca-certificates.crt. Outgoing HTTPS requests from Endpoints will not check server certificates.
nginx: [emerg] unknown "endpoints_api_userinfo" variable
```
For some reason the endpoints_api_userinfo variable is not set. Not sure why.

When commenting out the proxy header like this:
```
# Begin Endpoints v2 Support
# proxy_set_header X-Endpoint-API-UserInfo $endpoints_api_userinfo;
# End Endpoints v2 Support
```
it works as expected (http/https) but obviously the `X-Endpoint-API-UserInfo` is not set.

I've been testing with the following command:
```
curl -d '{"message":"hello world"}' -H "content-type:application/json" -k http://146.148.30.62/echo\?key\=A....
```

Any idea what might go wrong? The service definition obviously works and authentication as well; just the userinfo is not getting set for some reason.

(we've not yet tested OAuth, perhaps `X-Endpoint-API-UserInfo` only works then?)

Kind regards,
Niels

**Comment by qiwzhang** [comment]
nginx.conf is outdated.   You don't need to use "proxy_set_header" in nginx.conf to set X-Endpoint-API-UserInfo anymore.  It will be set automatically as long as OAuth token is provided.

I will create PR to update the nginx.conf to remove that line.

**Comment by wlu2016** [comment]
FYI, the PR with the fix has been merged. Please let us know if you still run into any issue. You are right that X-Endpoint-API-UserInfo only works when you enable auth.

Thanks for reporting this problem.
