### ISSUE TITLE
GCE L7 Loadbalancer and readiness

### ISSUE THREAD

**Issue by ensonic** [GoogleCloudPlatform/endpoints-samples#35]
https://github.com/GoogleCloudPlatform/endpoints-samples/tree/master/k8s#using-gce-l7-load-balancer-with-esp
documents how to implement the health-checking required for the loadbalancer. Can you also link to the api implementation? Since the grpc is running on 8080, I don't see how one would actually serve the /health requests or is that done transparently via nginx?

The echo sample code/docker image are dead links (404).

**Comment by kyessenov** [comment]
There is a flag "-z" on ESP container that opens up a handler for health check request in nginx.
See here https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/nginx-auto.conf.template#L75

**Comment by ensonic** [comment]
Thanks!
