### ISSUE TITLE
Examples for k8s are wrong

### ISSUE THREAD

**Issue by FranOis** [GoogleCloudPlatform/endpoints-samples#41]
Various example yaml does not reflect the right way to setup on k8s.

One such example is the args for this file https://github.com/GoogleCloudPlatform/endpoints-samples/blob/master/k8s/esp_echo_http.yaml

It is the same thing on the google documentation on cloud endpoints, arguments passed should be -p -a -s -v etc.

Link to the google documentation that does not comply with the code in ESP: https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes

**Comment by kryzthov** [comment]
Hello,

To the best of my knowledge, the arguments described in the example and in the documentation are in agreement with the code in ESP: see the argument declarations here https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py#L396-L565

Are you saying that the command-lines in the examples and in the documentation are not working?
Thanks!

**Comment by FranOis** [comment]
Derp... Looks like I was constantly using dashes instead of underscore. Sorry about that.
