### ISSUE TITLE
ESP =? Extensible Service Proxy

### ISSUE THREAD

**Issue by Jofre** [GoogleCloudPlatform/endpoints-samples#48]
https://github.com/GoogleCloudPlatform/endpoints-samples/blob/master/gce/README.md#L28

I think there is some confusion here, as ESP usually refers to [Extensible Service Proxy][1], and not "Endpoints Server Proxy" as suggested by the README. There are [other instances][2] using this naming.

Maybe we are areferring to different things, but if ESP means [Extensible Service Proxy][1], we sould unify the naming conventions to avoid confusion.

[1]: https://cloud.google.com/endpoints/docs/openapi/glossary#extensible_service_proxy
[2]: https://github.com/GoogleCloudPlatform/endpoints-samples/blob/master/k8s/render.py#L59

**Comment by simonz130** [comment]
Thanks for the suggestion, Jofre. I'm closing it as it was addressed already.
