### ISSUE TITLE
Fix duplicate ports in kubernetes/echo.yaml

### ISSUE THREAD

**Issue by nareddyt** [GoogleCloudPlatform/endpoints-samples#62]
https://github.com/GoogleCloudPlatform/endpoints-samples/blob/9aba1fe65c1ac10fca1060f44e16d5ca4955b4d2/kubernetes/echo.yaml#L58-L63

This section looks pretty wrong: 
- `ports` defined twice for ESP container.
- `volumeMounts` under ports, should be top-level for ESP container.

@qiwzhang: Which tutorial is this file used in? It seems like we did not catch the error in our testing (thought we haven't all finished testing yet).

**Comment by TAOXUY** [comment]
https://github.com/GoogleCloudPlatform/endpoints-samples/pull/63
